import 'package:json_annotation/json_annotation.dart';

part 'todo.g.dart';

/// Todo model for the frontend.
///
/// Uses snake_case for JSON serialization to match backend API.
@JsonSerializable(fieldRename: FieldRename.snake)
class Todo {
  Todo({
    required this.id,
    required this.title,
    this.description,
    this.completed = false,
    this.priority = 3,
    this.dueDate,
    required this.updatedAt,
    this.deletedAt,
    this.deletedAtLocal,
  });

  /// Unique identifier (UUID), generated by the client.
  final String id;

  /// Todo title (required).
  final String title;

  /// Optional description.
  final String? description;

  /// Whether the todo is completed.
  final bool completed;

  /// Priority level (1-5, where 1 is highest).
  final int priority;

  /// Optional due date.
  final DateTime? dueDate;

  /// Last update timestamp (set by server).
  final DateTime updatedAt;

  /// Soft delete timestamp from server.
  final DateTime? deletedAt;

  /// Local delete timestamp (before sync).
  final DateTime? deletedAtLocal;

  factory Todo.fromJson(Map<String, dynamic> json) => _$TodoFromJson(json);

  Map<String, dynamic> toJson() => _$TodoToJson(this);

  /// Creates a copy with updated fields.
  Todo copyWith({
    String? id,
    String? title,
    String? description,
    bool? completed,
    int? priority,
    DateTime? dueDate,
    DateTime? updatedAt,
    DateTime? deletedAt,
    DateTime? deletedAtLocal,
  }) {
    return Todo(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      completed: completed ?? this.completed,
      priority: priority ?? this.priority,
      dueDate: dueDate ?? this.dueDate,
      updatedAt: updatedAt ?? this.updatedAt,
      deletedAt: deletedAt ?? this.deletedAt,
      deletedAtLocal: deletedAtLocal ?? this.deletedAtLocal,
    );
  }

  @override
  String toString() => 'Todo(id: $id, title: $title, completed: $completed)';
}
