import 'package:drift/drift.dart';
import 'package:offline_first_sync_drift/offline_first_sync_drift.dart';

import '../../models/todo.dart';

/// Drift table definition for todos.
///
/// Uses [SyncColumns] mixin to add synchronization fields:
/// - updatedAt
/// - deletedAt
/// - deletedAtLocal
@UseRowClass(Todo, generateInsertable: true)
class Todos extends Table with SyncColumns {
  /// Unique identifier (UUID), generated by the client.
  TextColumn get id => text()();

  /// Todo title (required).
  TextColumn get title => text().withLength(min: 1, max: 255)();

  /// Optional description.
  TextColumn get description => text().nullable()();

  /// Whether the todo is completed.
  BoolColumn get completed => boolean().withDefault(const Constant(false))();

  /// Priority level (1-5, where 1 is highest).
  IntColumn get priority => integer().withDefault(const Constant(3))();

  /// Optional due date.
  DateTimeColumn get dueDate => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
